In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('bball_seasons.csv')

C:\Users\LiamDeaton\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
df.head()

,player_name,season,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,Kareem Abdul-Jabbar,1980,1.0,1.0,1979-10-12,32-179,LAL,@,SDC,W (+1),...,6,10,4,2,3,4,2,29,25.1,NaN
1,Kareem Abdul-Jabbar,1980,2.0,2.0,1979-10-16,32-183,LAL,NaN,CHI,W (+9),...,10,10,2,0,4,1,5,21,20.5,NaN
2,Kareem Abdul-Jabbar,1980,3.0,3.0,1979-10-17,32-184,LAL,@,SEA,L (-2),...,4,7,4,NaN,NaN,3,2,23,NaN,NaN
3,Kareem Abdul-Jabbar,1980,4.0,4.0,1979-10-19,32-186,LAL,NaN,POR,L (-17),...,8,13,0,1,2,9,2,22,7.7,NaN
4,Kareem Abdul-Jabbar,1980,5.0,5.0,1979-10-21,32-188,LAL,NaN,SEA,W (+9),...,12,20,3,1,2,6,2,23,18,NaN

In [9]:
df.

<bound method NDFrame.describe of                 player_name  season    Rk     G        Date     Age   Tm  \
0       Kareem Abdul-Jabbar    1980   1.0   1.0  1979-10-12  32-179  LAL
1       Kareem Abdul-Jabbar    1980   2.0   2.0  1979-10-16  32-183  LAL
2       Kareem Abdul-Jabbar    1980   3.0   3.0  1979-10-17  32-184  LAL
3       Kareem Abdul-Jabbar    1980   4.0   4.0  1979-10-19  32-186  LAL
4       Kareem Abdul-Jabbar    1980   5.0   5.0  1979-10-21  32-188  LAL
...                     ...     ...   ...   ...         ...     ...  ...
635728          Ivica Zubac    2020  68.0  68.0  2020-08-06  23-141  LAC
635729          Ivica Zubac    2020  69.0  69.0  2020-08-08  23-143  LAC
635730          Ivica Zubac    2020  70.0  70.0  2020-08-09  23-144  LAC
635731          Ivica Zubac    2020  71.0  71.0  2020-08-12  23-147  LAC
635732          Ivica Zubac    2020  72.0  72.0  2020-08-14  23-149  LAC

       Unnamed: 5  Opp Unnamed: 7  ... DRB TRB AST  STL  BLK TOV PF PTS  GmSc  \
0               @  SDC     W (+1)  ...   6  10   4    2    3   4  2  29  25.1
1             NaN  CHI     W (+9)  ...  10  10   2    0    4   1  5  21  20.5
2               @  SEA     L (-2)  ...   4   7   4  NaN  NaN   3  2  23   NaN
3             NaN  POR    L (-17)  ...   8  13   0    1    2   9  2  22   7.7
4             NaN  SEA     W (+9)  ...  12  20   3    1    2   6  2  23    18
...           ...  ...        ...  ...  ..  ..  ..  ...  ...  .. ..  ..   ...
635728          @  DAL    W (+15)  ...   9  15   1    0    1   0  1  21  25.5
635729          @  POR     W (+5)  ...   6  12   4    0    0   0  1   9  14.3
635730        NaN  BRK     L (-9)  ...  10  15   2    0    1   0  3   8  11.4
635731          @  DEN    W (+13)  ...   8  12   2    0    0   0  3  15  16.5
635732        NaN  OKC     W (+4)  ...   3   4   0    0    1   1  1   6   5.6

        +/-
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
635728   +8
635729   -4
635730   -9
635731   +5
635732   +8

[635733 rows x 32 columns]>